Numpy

In [2]:
# Importamos numpy como np
import numpy as np

In [3]:
# Podemos crear arrays de una dimension con la funcion np.array()
array_unidim = np.array([1,2,3,4,5])

# Array de 2 dimensiones
array_bidim = np.array([[1,2,3], [4,5,6]])

# Array de tres dimensiones
array_tridim = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

Para cada uno de estos array, podemos obtener sus propiedades:

In [4]:
# Atributos array unidimensional
array_unidim.shape, array_unidim.ndim, array_unidim.dtype, array_unidim.size, type(array_unidim)

((5,), 1, dtype('int64'), 5, numpy.ndarray)

In [5]:
# Atributos array bidimensional
array_bidim.shape, array_bidim.ndim, array_bidim.dtype, array_bidim.size, type(array_bidim)

((2, 3), 2, dtype('int64'), 6, numpy.ndarray)

In [6]:
# Atributos array tridimensional
array_tridim.shape, array_tridim.ndim, array_tridim.dtype, array_tridim.size, type(array_tridim)

((2, 2, 3), 3, dtype('int64'), 12, numpy.ndarray)

Pandas

In [7]:
# Importamos Pandas
import pandas as pd

In [8]:
datos = pd.DataFrame(array_bidim)
datos

0  1  2
0  1  2  3
1  4  5  6

In [9]:
# Creamos un array 4x3, formado solamente por 1 (unos)
array_ones = np.ones((4,3))
array_ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [10]:
# Creamos una array de tamaño 2x4x3, formado unicamente por 0 (ceros)
array_zeros = np.zeros((2,4,3))
array_zeros

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [11]:
# Creamos un array de números en el rango de 0 a 100, con paso de 5
array_rango = np.arange(0,101, 5)
array_rango

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100])

In [12]:
# Creamos un array de numeros alñeatorios enteros comprendidos entre 0 y 10, de tamaño (2,5)
array_randint = np.random.randint(0,10, (2,5))
array_randint

array([[6, 0, 3, 8, 6],
       [8, 8, 5, 7, 9]])

In [13]:
# Creamos un array de numeros aleatorios decimales entre 0 y 1, e tamaño (3,5)
array_random = np.random.random((3,5))
array_random

array([[0.52011802, 0.49034084, 0.27140366, 0.71149398, 0.91742656],
       [0.35742473, 0.32734478, 0.08782165, 0.09141427, 0.92882829],
       [0.7989974 , 0.67902681, 0.6737923 , 0.31028956, 0.94480949]])

In [14]:
# Establecemos la 'semilla' de numeros aleatorios en 27
np.random.seed(27)

# Creamos un array de numeros aleatorios enteros comprendidos entre 0 y 10, de tamaño (3,5)
array_randint_seed = np.random.randint(0,10, (3,5))
array_randint_seed


array([[3, 8, 8, 8, 0],
       [5, 8, 9, 1, 2],
       [1, 1, 4, 6, 3]])

In [15]:
# Encontramos los valores unicos del array anterior
np.unique(array_randint_seed)

array([0, 1, 2, 3, 4, 5, 6, 8, 9])

In [16]:
# Extraemos el elemento e indice 1 del array anterior
array_randint_seed[1]

array([5, 8, 9, 1, 2])

In [17]:
# Extraemos las 2 primeras filas
array_randint_seed[:2]

array([[3, 8, 8, 8, 0],
       [5, 8, 9, 1, 2]])

In [18]:
# Extraemos los dos primeros datos de las dos primeras filas
array_randint_seed[:2, 1:3]

array([[8, 8],
       [8, 9]])

In [19]:
# Creamos dos arrays de tamaño 3x4: uno relleno de numeros aleatorios entre 0 y 10, y otro rellenop de unos
array_5 = np.random.randint(0,10, (3,4))
array_6 = np.ones((3,4))

In [20]:
# Sumamos los 2 array
array_5 + array_6

array([[4., 1., 6., 4.],
       [4., 7., 8., 3.],
       [8., 9., 6., 8.]])

In [21]:
# Creamos ahora un array de tamaño (4,3) lleno de unos
array_7 = np.ones((4,3))

In [22]:
# intentamos sumar
array_6 + array_7

ValueError: ignored

In [24]:
# Entonces crearemos otro array de tamaño (4,3), llenos de unos
array_8 = np.ones((4,3))

In [25]:
# Restamos
array_7 - array_8

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [26]:
# Creamos dos array de tamaño 3x3 con numeros aleatorios del 1 al 5
array_9 = np.random.randint(1,5, (3,3))
array_10 = np.random.randint(1,5, (3,3))

In [27]:
# invocamos arra_9
array_9

array([[2, 3, 4],
       [1, 4, 4],
       [2, 3, 4]])

In [28]:
# Invocamos array_10
array_10

array([[2, 1, 4],
       [4, 1, 2],
       [2, 4, 1]])

In [29]:
# Multiplicamos 
array_9 * array_10

array([[ 4,  3, 16],
       [ 4,  4,  8],
       [ 4, 12,  4]])

In [30]:
# Elevamos el array 9 al cuadrado
array_9**2

array([[ 4,  9, 16],
       [ 1, 16, 16],
       [ 4,  9, 16]])

In [31]:
# Buscamos la raiz cuadrada
np.sqrt(array_10)

array([[1.41421356, 1.        , 2.        ],
       [2.        , 1.        , 1.41421356],
       [1.41421356, 2.        , 1.        ]])

In [32]:
# Hallamos promedio de los valores
array_9.mean()

3.0

In [33]:
array_9.max()

4

In [34]:
array_9.min()

1

In [35]:
# Redimensionamos el array
array_11 = array_9.reshape((9,1))
array_11

array([[2],
       [3],
       [4],
       [1],
       [4],
       [4],
       [2],
       [3],
       [4]])

In [36]:
# Transponemos el array_11
array_11.T

array([[2, 3, 4, 1, 4, 4, 2, 3, 4]])

In [37]:
# Comparamos el arra_9 y array_10 para saber cuales son mayores
array_12 = array_9 > array_10
array_12

array([[False,  True, False],
       [False,  True,  True],
       [False, False,  True]])

In [38]:
# Veamos sus nuevos tipos de datos
array_12.dtype

dtype('bool')

In [39]:
# Algunos de los elementos del array_ es iguual su equivalente del array _10
array_9 == array_10

array([[ True, False,  True],
       [False, False, False],
       [ True, False, False]])

In [40]:
# Compramos nuevamente ambos arrays, en esta ocasión com >=
array_9 >= array_10

array([[ True,  True,  True],
       [False,  True,  True],
       [ True, False,  True]])

In [41]:
# Buscamos los elementos del array_9 que son mayores a 2
array_9 > 2

array([[False,  True,  True],
       [False,  True,  True],
       [False,  True,  True]])

In [42]:
# Oredenamos de menor a mayor los elementos dentro del array_p
np.sort(array_9)

array([[2, 3, 4],
       [1, 4, 4],
       [2, 3, 4]])